routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonasController;
use App\Http\Controllers\MedicamentosController;
use App\Http\Controllers\PrescripcionesController;


/*
La idea fue experimentar con las rutas de laravel 

comence haciendo las vistas desordenadas 
*/

Route::get('/',[PersonasController::class,'index'])->name('index');
Route::get('/personas',[PersonasController::class,'nuevaPersona'])->name('personas');
Route::post('/',[PersonasController::class,'store'])->name('insertarPersona');
Route::get('/personas-tabla',[PersonasController::class,'tablaPersonas'])->name('tablaPersonas');
Route::get('/edit-personas/{persona}',[PersonasController::class,'edit'])->name('editarPersona');
Route::delete('/eliminar/{persona}',[PersonasController::class,'destroy'])->name('eliminarPersona');
Route::patch('/edit-personas/{persona}',[PersonasController::class,'update'])->name('persona.edit');

/* vistas por convención */
Route::get('/medicamentos/crear',[MedicamentosController::class,'create'])->name('medicamento.create');
Route::get('/medicamentos/tabla',[MedicamentosController::class,'index'])->name('medicamento.index');
Route::post('/medicamento/insert',[MedicamentosController::class,'store'])->name('medicamento.store');
Route::get('/medicamentos/editar/{medicamento}',[MedicamentosController::class,'edit'])->name('medicamento.edit');
Route::patch('/medicamentos/update/{medicamento}',[MedicamentosController::class,'update'])->name('medicamento.update');
Route::delete('/medicamentos/delete/{medicamento}',[MedicamentosController::class,'delete'])->name('medicamento.delete');

/* Vistas producidas por laravel*/
Route::resource('/prescripciones', PrescripcionesController::class);

//adicionales para los filtros
Route::post('prescripciones/buscar-dni',[PrescripcionesController::class,'BuscarDni'])->name('buscarDni');
Route::post('prescripciones/buscar-medicamento',[PrescripcionesController::class,'BuscarMedicamento'])->name('buscarMedicamento');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('pestaña')</title>
    <link rel="icon" href="https://www.integrandosalud.com/src-v2/public/bootstrap/img/favicon/favicon.ico" type="image/x-icon">
    @vite('resources/css/app.css')
</head>

<body class="bg-slate-100">

    <nav class="font-serif p-1 bg-gradient-to-r from-blue-800  to-cyan-400 top-0 left-0 border-b border-gray-200 content-center" id="nav">
        <div class="grid grid-cols-3 content-center ">
            <div></div>
            <div class="flex justify-center items-center text-white  text-2xl md:text-5xl "><label id="titulo">@yield('titulo')</label> </div>
            <div class="my-1 flex justify-around md:mx-3"> 
                    <a href="{{route('index')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Menu</a>
                    <a href="{{route('personas')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Crear</a>
                    <a href="{{route('tablaPersonas')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Tabla</a>
            </div>
        </div>
    </nav>

    @yield('content')

    
</body>
</html>

resources/views/layouts/appMedicamentos.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('pestaña')</title>
    <link rel="icon" href="https://www.integrandosalud.com/src-v2/public/bootstrap/img/favicon/favicon.ico" type="image/x-icon">
    @vite('resources/css/app.css')
</head>

<body class="bg-slate-100">

    <nav class="font-serif p-1 bg-gradient-to-r from-blue-800  to-cyan-400 top-0 left-0 border-b border-gray-200 content-center" id="nav">
        <div class="grid grid-cols-3 content-center ">
            <div></div>
            <div class="flex justify-center items-center text-white  text-2xl md:text-5xl "><label id="titulo">@yield('titulo')</label> </div>
            <div class="my-1 flex justify-around md:mx-3"> 
                    <a href="{{route('index')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Menu</a>
                    <a href="{{route('medicamento.create')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Crear</a>
                    <a href="{{route('medicamento.index')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Tabla</a>
                    
            </div>
        </div>
    </nav>

    @yield('content')

    
</body>
</html>

resources/views/layouts/appPrescripciones.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('pestaña')</title>
    <link rel="icon" href="https://www.integrandosalud.com/src-v2/public/bootstrap/img/favicon/favicon.ico" type="image/x-icon">
    @vite('resources/css/app.css')
</head>

<body class="bg-slate-100">

    <nav class="font-serif p-1 bg-gradient-to-r from-blue-800  to-cyan-400 top-0 left-0 border-b border-gray-200 content-center" id="nav">
        <div class="grid grid-cols-3 content-center ">
            <div></div>
            <div class="flex justify-center items-center text-white  text-2xl md:text-5xl "><label id="titulo">@yield('titulo')</label> </div>
            <div class="my-1 flex justify-around md:mx-3"> 
                    <a href="{{route('index')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Menu</a>
                    <a href="{{route('prescripciones.create')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Crear</a>
                    <a href="{{route('prescripciones.index')}}" class="text-black font-semibold text-xl hover:bg-cyan-200 px-1 py-1 rounded">Tabla</a>       
            </div>
        </div>
    </nav>

    @yield('content')

    
</body>
</html>