routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonasController;
use App\Http\Controllers\MedicamentosController;
use App\Http\Controllers\PrescripcionesController;


/*
La idea fue experimentar con las rutas de laravel 

comence haciendo las vistas desordenadas 
*/

Route::get('/',[PersonasController::class,'index'])->name('index');
Route::get('/personas',[PersonasController::class,'nuevaPersona'])->name('personas');
Route::post('/',[PersonasController::class,'store'])->name('insertarPersona');
Route::get('/personas-tabla',[PersonasController::class,'tablaPersonas'])->name('tablaPersonas');
Route::get('/edit-personas/{persona}',[PersonasController::class,'edit'])->name('editarPersona');
Route::delete('/eliminar/{persona}',[PersonasController::class,'destroy'])->name('eliminarPersona');
Route::patch('/edit-personas/{persona}',[PersonasController::class,'update'])->name('persona.edit');

/* vistas por convención */
Route::get('/medicamentos/crear',[MedicamentosController::class,'create'])->name('medicamento.create');
Route::get('/medicamentos/tabla',[MedicamentosController::class,'index'])->name('medicamento.index');
Route::post('/medicamento/insert',[MedicamentosController::class,'store'])->name('medicamento.store');
Route::get('/medicamentos/editar/{medicamento}',[MedicamentosController::class,'edit'])->name('medicamento.edit');
Route::patch('/medicamentos/update/{medicamento}',[MedicamentosController::class,'update'])->name('medicamento.update');
Route::delete('/medicamentos/delete/{medicamento}',[MedicamentosController::class,'delete'])->name('medicamento.delete');

/* Vistas producidas por laravel*/
Route::resource('/prescripciones', PrescripcionesController::class);

//adicionales para los filtros
Route::post('prescripciones/buscar-dni',[PrescripcionesController::class,'BuscarDni'])->name('buscarDni');
Route::post('prescripciones/buscar-medicamento',[PrescripcionesController::class,'BuscarMedicamento'])->name('buscarMedicamento');

app/Http/Controllers/PrescripcionesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\PersonaMedicamento;
use App\Models\Persona;
use App\Models\Medicamento;

class PrescripcionesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('Prescripciones.tablePrescripciones',['posts'=>PersonaMedicamento::orderBy('id')->paginate(5)]);
        
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('Prescripciones.createPrescripciones',['personas'=>Persona::all()],['medicamentos'=>Medicamento::all()]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'observaciones' => 'required',
            'paciente' => 'required',
            'medicamento' => 'required',
        ]);

        $prescipcion= new PersonaMedicamento;
        $prescipcion->observaciones=$request->observaciones;
        $prescipcion->persona_id=$request->paciente;
        $prescipcion->medicamento_id=$request->medicamento;
        $prescipcion->save();
        return redirect()->route('prescripciones.index',['posts'=>PersonaMedicamento::orderBy('id')->paginate(5)]);

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $prescripcion= PersonaMedicamento::find($id);
        return view('Prescripciones.editPrescripcion',['prescripcion'=>$prescripcion,'medicamentos'=>Medicamento::all(),'personas'=>Persona::all()]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $prescripcion= PersonaMedicamento::find($id);
        $prescripcion->observaciones=$request->observaciones;
        $prescripcion->persona_id=$request->paciente;
        $prescripcion->medicamento_id=$request->medicamento;
        $prescripcion->save();
        return  redirect()->route('prescripciones.index',['posts'=>PersonaMedicamento::orderBy('id')->paginate(5)]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $prescripcion= PersonaMedicamento::find($id);
        $prescripcion->delete();
        return  redirect()->route('prescripciones.index',['posts'=>PersonaMedicamento::orderBy('id')->paginate(5)]);
    }

    public function BuscarDni(Request $request){
        $prescripciones=PersonaMedicamento::join('personas','persona_medicamento.persona_id','=','personas.id')->where('personas.dni',$request->dni)->paginate(30);
        return  view('Prescripciones.tablePrescripciones',['posts'=>$prescripciones]);
    }

    public function BuscarMedicamento(Request $request){
        $nombreComercial = $request->input('medicamento');
        $personaMedicamentos = PersonaMedicamento::whereHas('medicamento', function($query) use ($nombreComercial) {
            $query->where('nombre_comercial','LIKE','%'. $nombreComercial .'%');
        })->paginate(100);
        return view('Prescripciones.tablePrescripciones',['posts'=>$personaMedicamentos]);;

    }
}

resources/views/Prescripciones/createPrescripciones.blade.php
@extends('layouts.appPrescripciones')

@section('pestaña','prescripciones')

@section('titulo','PRESCRIPCIONES')

@section('content')
<form action="{{route('prescripciones.store')}}" method="POST">
    @csrf
    <div class="bg-slate-50 font-serif block container mx-auto rounded border border-gray-600 w-80 sm:w-1/2 xl:w-1/3  rounded mt-20 ">
        <div class="">
            <div class="bg-cyan-700 flex justify-center algin-center border-green text-4xl text-white p-2 ">
                <label> Nueva Receta </label>
            </div>
            <div class="p-2">

                <div class="mt-3">
                    <label data-te-select-label-ref for="countries" class=" ml-2 text-sm font-medium text-gray-900">Paciente</label>
                    <select data-te-select-init  id="paciente" name="paciente" class="px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-xl focus:ring-1">
                        <option hidden selected>Selecciona un paciente</option>
                        @foreach ($personas as $persona)
                            <option value="{{$persona->id}}">{{$persona->nombre}} {{$persona->apellido}}</option>
                        @endforeach
                    </select>
                    
                </div>

                <div class="">
                    <label data-te-select-label-ref for="countries" class=" ml-2 text-sm font-medium text-gray-900">Medicamento</label>
                    <select data-te-select-init  id="medicamento" name="medicamento" class="px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-xl focus:ring-1">
                        <option hidden selected>Selecciona un medicamento</option>
                        @foreach ($medicamentos as $medicamento)
                            <option value="{{$medicamento->id}}">{{$medicamento->nombre_comercial}}</option>
                        @endforeach
                    </select>
                    
                </div>

                <div class="mt-3">
                    <input type="text" id="observaciones" name="observaciones" class=" px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-xl focus:ring-1" placeholder="observaciones" />
                </div>

            </div>
            <div class="flex justify-center align-center">
                <button type="submit" class=" bg-gradient-to-r from-green-400 to-blue-500 shadow-xl text-white font-bold border border-gray-200 hover:from-pink-500 hover:to-yellow-500 focus:outline-none focus:ring px-6 py-2 rounded-full m-2">Guardar</button>
            </div> 
            
            
            
        </div>
    </div>
</form>
@endsection

resources/views/Prescripciones/editPrescripcion.blade.php
@extends('layouts.appPrescripciones')
@section('pestaña','prescripciones')
@section('titulo','PRESCRIPCIONES')

@section('content')

<form action="{{route('prescripciones.update',$prescripcion)}}" method="POST">
    @csrf
    @method('PATCH')
    <div class="bg-slate-50 font-serif block container mx-auto rounded border border-gray-600 w-80 sm:w-1/2 xl:w-1/3  rounded mt-20 ">
        <div class="">
            <div class="bg-cyan-700 flex justify-center algin-center border-green text-4xl text-white p-2 ">
                <label> Nueva Receta </label>
            </div>
            <div class="p-2">

                <div class="mt-3">
                    <label data-te-select-label-ref for="countries" class=" ml-2 text-sm font-medium text-gray-900">Paciente</label>
                    <select data-te-select-init  id="paciente" name="paciente" class="px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-xl focus:ring-1">
                        @foreach ($personas as $persona)
                            <option value="{{$persona->id}}"
                                @if ($persona->id==$prescripcion->persona_id)
                                    selected
                                @endif > {{$persona->nombre}} {{$persona->apellido}}
                            </option>
                        @endforeach
                    </select>
                    
                </div>

                <div class="">
                    <label data-te-select-label-ref for="countries" class=" ml-2 text-sm font-medium text-gray-900">Medicamento</label>
                    <select data-te-select-init  id="medicamento" name="medicamento" class="px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-xl focus:ring-1">
                        @foreach ($medicamentos as $medicamento)
                            <option value="{{$medicamento->id}}" 
                                @if ($medicamento->id==$prescripcion->medicamento_id)
                                    selected
                                @endif>{{$medicamento->nombre_comercial}}
                            </option>
                        @endforeach
                    </select>
                    
                </div>

                <div class="mt-3">
                    <input type="text" id="observaciones" name="observaciones" class=" px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-xl focus:ring-1" placeholder="observaciones" value="{{$prescripcion->observaciones}}"/>
                </div>

                

            </div>
            <div class="flex justify-center align-center">
                <button type="submit" class=" bg-gradient-to-r from-green-400 to-blue-500 shadow-xl text-white font-bold border border-gray-200 hover:from-pink-500 hover:to-yellow-500 focus:outline-none focus:ring px-6 py-2 rounded-full m-2">Guardar</button>
            </div> 
            
            
            
        </div>
    </div>
</form>



   

    


    
@endsection

resources/views/Prescripciones/tablePrescripciones.blade.php
@extends('layouts.appPrescripciones')

@section('pestaña','prescripciones')

@section('titulo','PRESCRIPCIONES')

@section('content')
<div class="container mx-auto mt-10">
    
    <div class="flex flex-col">
        <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
          <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <div class="flex justify-around px-10">
                    <form action="{{route('buscarDni')}}" method="POST" class="my-4 w-1/3">
                        @csrf   
                        <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only ">Search</label>
                        <div class="relative">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                            </div>
                            <input name="dni" id="dni" type="search" class="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500    " placeholder="Filtrar por dni" required>
                            <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 ">Buscar</button>
                        </div>
                    </form>
                    <form action="{{route('buscarMedicamento')}}" method="POST" class="my-4 w-1/3">   
                        @csrf
                        <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only ">Search</label>
                        <div class="relative">
                            <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                            </div>
                            <input type="search" name="medicamento" id="medicamento" class="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500    " placeholder="Buscar por medicamento" required>
                            <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 ">Buscar</button>
                        </div>
                    </form>
                </div>
                
              <table class="min-w-full ">
                <thead class="bg-gray-200 border-b">
                  <tr class="">
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                      ID
                    </th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                      Nombre
                    </th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                      Apellido
                    </th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                      DNI
                    </th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                      Observaciones
                    </th>
                    <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                      
                    </th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($posts as $post)
                    <tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            {{$post->id}}
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            {{$post->persona->nombre}}
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            {{$post->persona->apellido}}
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            {{$post->persona->dni}}
                        </td>
                        <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                            {{$post->observaciones}}
                        </td>
                        <td class="flex py-4 " >
                          <a href="{{route('prescripciones.edit',$post)}}" title="Editar">
                          <svg class="h-8 w-8 text-green-500 hover:bg-white"  viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M9 7 h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3" />  <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3" />  <line x1="16" y1="5" x2="19" y2="8" /></svg>
                          </a>
                          <form action="{{route('prescripciones.destroy',$post)}}" method="POST">
                              @csrf
                              @method('DELETE')
                              <button type="submit" onclick="if(!confirm('desea eliminar?')){
                                prevent.default()
                              }" title="Eliminar">
                                  <svg class="h-8 w-8 text-red-600"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" />  <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" transform="rotate(120 12 13)" />  <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" transform="rotate(240 12 13)" /></svg>
                              </button>
                          </form>
                        </td>
                    </tr>
                    
                    @endforeach
                    
                </tbody>
              </table>
              {{$posts->links('pagination::tailwind')}}              
            </div>
          </div>
        </div>
      </div>
</div>
@endsection